/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ImageGallery {
    }
}
declare global {
    interface HTMLImageGalleryElement extends Components.ImageGallery, HTMLStencilElement {
    }
    var HTMLImageGalleryElement: {
        prototype: HTMLImageGalleryElement;
        new (): HTMLImageGalleryElement;
    };
    interface HTMLElementTagNameMap {
        "image-gallery": HTMLImageGalleryElement;
    }
}
declare namespace LocalJSX {
    interface ImageGallery {
    }
    interface IntrinsicElements {
        "image-gallery": ImageGallery;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "image-gallery": LocalJSX.IntrinsicElements["image-gallery"] & JSXBase.HTMLAttributes<HTMLImageGalleryElement>;
        }
    }
}
